/**
 * -----------------------------------------------------------------------------
 * Generated by Pure Clean Architecture CLI.
 *
 * This file is an example implementation provided to demonstrate
 * how this layer works within the architecture.
 *
 * It is only a starting point — you are free to modify, replace,
 * or delete it as your project evolves.
 * -----------------------------------------------------------------------------
 */

import { createHttp } from '@shared_kernel/infrastructure/http';

import type { CreateUserUseCase, UpdateUserUseCase, GetUsersUseCase, GetUserUseCase } from './application';
import { UserEndpoints, createUserComposition } from './user.composition';
import type { UserDeps } from './user.composition';

export type { CreateUserDto, UpdateUserDto, UserDto } from './application';
export { UserEndpoints };

export interface UserContext {
  readonly createUser: CreateUserUseCase;
  readonly updateUser: UpdateUserUseCase;
  readonly getUsers: GetUsersUseCase;
  readonly getUser: GetUserUseCase;
}

export function createUserEntrypoint(overrides?: Partial<UserDeps>): UserContext {
  const container: UserDeps = {
    http: overrides?.http ?? createHttp(UserEndpoints),
  };
  return createUserComposition(container);
}
