/**
 * -----------------------------------------------------------------------------
 * Generated by Pure Clean Architecture CLI.
 *
 * This file is an example implementation provided to demonstrate
 * how this layer works within the architecture.
 *
 * It is only a starting point — you are free to modify, replace,
 * or delete it as your project evolves.
 * -----------------------------------------------------------------------------
 */

import { createComposition } from '@shared_kernel/composition';
import type { IHttp } from '@shared_kernel/contracts';

import { CreateUserUseCase, UpdateUserUseCase, GetUsersUseCase, GetUserUseCase } from './application';
import { UserRepository, UserEndpoints } from './infrastructure';

export { UserEndpoints };

export interface UserDeps {
  http: IHttp<typeof UserEndpoints>;
}

export const createUserComposition = createComposition<
  UserDeps,
  UserRepository,
  {
    createUser: CreateUserUseCase;
    updateUser: UpdateUserUseCase;
    getUsers: GetUsersUseCase;
    getUser: GetUserUseCase;
  }
>({
  createServices: (repository) => ({
    createUser: new CreateUserUseCase(repository),
    updateUser: new UpdateUserUseCase(repository),
    getUsers: new GetUsersUseCase(repository),
    getUser: new GetUserUseCase(repository),
  }),
  createRepository: ({ http }) => new UserRepository(http),
});
