/**
 * -----------------------------------------------------------------------------
 * Generated by Pure Clean Architecture CLI.
 *
 * This file is an example implementation provided to demonstrate
 * how this layer works within the architecture.
 *
 * It is only a starting point — you are free to modify, replace,
 * or delete it as your project evolves.
 * -----------------------------------------------------------------------------
 */

import type { IUserRepository, CreateUserData, UpdateUserData } from './user.repository';

export type { IUserRepository, CreateUserData, UpdateUserData };
