/**
 * -----------------------------------------------------------------------------
 * Generated by Pure Clean Architecture CLI.
 *
 * This file is an example implementation provided to demonstrate
 * how this layer works within the architecture.
 *
 * It is only a starting point — you are free to modify, replace,
 * or delete it as your project evolves.
 * -----------------------------------------------------------------------------
 */

export interface CreateUserDto {
    readonly name: string;
    readonly email: string;
}

export interface UpdateUserDto {
    readonly name?: string;
    readonly email?: string;
    readonly id: string;
}

export interface UserDto {
    readonly name: string;
    readonly email: string;
    readonly id: string;
}
