/**
 * -----------------------------------------------------------------------------
 * Generated by Pure Clean Architecture CLI.
 *
 * This file is an example implementation provided to demonstrate
 * how this layer works within the architecture.
 *
 * It is only a starting point — you are free to modify, replace,
 * or delete it as your project evolves.
 * -----------------------------------------------------------------------------
 */

import type { UserDto } from './user.dto';

export interface CreateUserData {
  readonly name: string;
  readonly email: string;
}

export interface UpdateUserData {
  readonly name?: string;
  readonly email?: string;
}

export interface IUserRepository {
  create(params: { body: CreateUserData }): Promise<UserDto>;
  update(params: { pathParams: { id: string }; body: UpdateUserData }): Promise<UserDto>;
  findById(params: { pathParams: { id: string } }): Promise<UserDto>;
  findAll(): Promise<UserDto[]>;
  delete(params: { pathParams: { id: string } }): Promise<void>;
}
