/**
 * -----------------------------------------------------------------------------
 * Generated by Pure Clean Architecture CLI.
 *
 * This file is an example implementation provided to demonstrate
 * how this layer works within the architecture.
 *
 * It is only a starting point — you are free to modify, replace,
 * or delete it as your project evolves.
 * -----------------------------------------------------------------------------
 */

import type { IHttp } from '@shared_kernel/contracts';

import type { IUserRepository } from '../domain';
import type { UserEndpoints } from './user.endpoints';

export class UserRepository implements IUserRepository {
  constructor(private readonly http: IHttp<typeof UserEndpoints>) {}

  public create: IUserRepository['create'] = async ({ body }) => {
    return this.http.request({
      endpoint: 'CREATE_USER',
      method: 'POST',
      body,
    });
  };

  public update: IUserRepository['update'] = async ({ pathParams, body }) => {
    return this.http.request({
      endpoint: 'UPDATE_USER',
      method: 'PATCH',
      pathParams,
      body,
    });
  };

  public findById: IUserRepository['findById'] = async ({ pathParams }) => {
    return this.http.request({
      endpoint: 'GET_USER',
      method: 'GET',
      pathParams,
    });
  };

  public delete: IUserRepository['delete'] = async ({ pathParams }) => {
    return this.http.request({
      endpoint: 'DELETE_USER',
      method: 'DELETE',
      pathParams,
    });
  };

  public findAll: IUserRepository['findAll'] = async () => {
    return this.http.request({
      endpoint: 'GET_USERS',
      method: 'GET',
    });
  };
}
