/**
 * -----------------------------------------------------------------------------
 * Generated by Pure Clean Architecture CLI.
 *
 * This file is an example implementation provided to demonstrate
 * how this layer works within the architecture.
 *
 * It is only a starting point — you are free to modify, replace,
 * or delete it as your project evolves.
 * -----------------------------------------------------------------------------
 */

export type UserEndpoints = typeof UserEndpoints;

export const UserEndpoints = {
    UPDATE_USER: '/api/users/:id',
    DELETE_USER: '/api/users/:id',
    GET_USER: '/api/users/:id',
    CREATE_USER: '/api/users',
    GET_USERS: '/api/users',
} as const;
