/**
 * -----------------------------------------------------------------------------
 * Generated by Pure Clean Architecture CLI.
 *
 * This file is an example implementation provided to demonstrate
 * how this layer works within the architecture.
 *
 * It is only a starting point — you are free to modify, replace,
 * or delete it as your project evolves.
 * -----------------------------------------------------------------------------
 */

import { createHttp } from '@shared_kernel/infrastructure/http';

import { OrderEndpoints, createOrderComposition } from './order.composition';
import type { OrderDeps } from './order.composition';
import type {
  GetOrdersByCustomerUseCase,
  GetOrdersByStatusUseCase,
  UpdateOrderStatusUseCase,
  CreateOrderUseCase,
  GetOrdersUseCase,
  GetOrderUseCase,
} from './application';

export type { CreateOrderDto, UpdateOrderStatusDto, OrderDto, OrderStatus, OrderItemDto } from './application';
export { OrderEndpoints };

export interface OrderContext {
  readonly getOrdersByCustomer: GetOrdersByCustomerUseCase;
  readonly getOrdersByStatus: GetOrdersByStatusUseCase;
  readonly updateOrderStatus: UpdateOrderStatusUseCase;
  readonly createOrder: CreateOrderUseCase;
  readonly getOrders: GetOrdersUseCase;
  readonly getOrder: GetOrderUseCase;
}

export function createOrderEntrypoint(overrides?: Partial<OrderDeps>): OrderContext {
  const container: OrderDeps = {
    http: overrides?.http ?? createHttp(OrderEndpoints),
  };
  return createOrderComposition(container);
}
