/**
 * -----------------------------------------------------------------------------
 * Generated by Pure Clean Architecture CLI.
 *
 * This file is an example implementation provided to demonstrate
 * how this layer works within the architecture.
 *
 * It is only a starting point — you are free to modify, replace,
 * or delete it as your project evolves.
 * -----------------------------------------------------------------------------
 */

import { createComposition } from '@shared_kernel/composition';
import type { IHttp } from '@shared_kernel/contracts';

import {
  GetOrdersByCustomerUseCase,
  UpdateOrderStatusUseCase,
  GetOrdersByStatusUseCase,
  CreateOrderUseCase,
  GetOrdersUseCase,
  GetOrderUseCase,
} from './application';
import { OrderRepository, OrderEndpoints } from './infrastructure';

export { OrderEndpoints };

export interface OrderDeps {
  http: IHttp<typeof OrderEndpoints>;
}

export const createOrderComposition = createComposition<
  OrderDeps,
  OrderRepository,
  {
    getOrdersByCustomer: GetOrdersByCustomerUseCase;
    updateOrderStatus: UpdateOrderStatusUseCase;
    getOrdersByStatus: GetOrdersByStatusUseCase;
    createOrder: CreateOrderUseCase;
    getOrders: GetOrdersUseCase;
    getOrder: GetOrderUseCase;
  }
>({
  createServices: (repository) => ({
    getOrdersByCustomer: new GetOrdersByCustomerUseCase(repository),
    getOrdersByStatus: new GetOrdersByStatusUseCase(repository),
    updateOrderStatus: new UpdateOrderStatusUseCase(repository),
    createOrder: new CreateOrderUseCase(repository),
    getOrders: new GetOrdersUseCase(repository),
    getOrder: new GetOrderUseCase(repository),
  }),
  createRepository: ({ http }) => new OrderRepository(http),
});
