import { Outlet, NavLink } from 'react-router-dom';

import './layout.css';

const Layout = () => {
    return (
        <div className="app">
            <nav className="nav">
                <div className="nav-inner">
                    <NavLink to="/" className="nav-logo">
                        <div className="nav-logo-icon">
                            <svg width="20" height="20" viewBox="0 0 28 28" fill="none">
                                <path
                                    d="M14 2L2 8v12l12 6 12-6V8L14 2z"
                                    stroke="currentColor"
                                    strokeWidth="1.5"
                                    strokeLinejoin="round"
                                />
                                <path
                                    d="M14 14L2 8m12 6l12-6m-12 6v12"
                                    stroke="currentColor"
                                    strokeWidth="1.5"
                                    strokeLinejoin="round"
                                />
                            </svg>
                        </div>
                        <span className="nav-logo-text">my-app</span>
                    </NavLink>

                    <div className="nav-links">
                        <NavLink
                            to="/"
                            end
                            className={({ isActive }) => `nav-link ${isActive ? 'nav-link-active' : ''}`}
                        >
                            Home
                        </NavLink>
                        <NavLink
                            to="/architecture"
                            className={({ isActive }) => `nav-link ${isActive ? 'nav-link-active' : ''}`}
                        >
                            Architecture
                        </NavLink>
                        <NavLink
                            to="/example"
                            className={({ isActive }) => `nav-link ${isActive ? 'nav-link-active' : ''}`}
                        >
                            Example
                        </NavLink>
                        <NavLink
                            to="/contact"
                            className={({ isActive }) => `nav-link ${isActive ? 'nav-link-active' : ''}`}
                        >
                            Contact
                        </NavLink>
                    </div>
                </div>
            </nav>

            <main className="main-content">
                <Outlet />
            </main>

            <footer className="footer">
                <div className="footer-inner">
                    <p>
                        Generated by <strong>Pure Clean Architecture CLI</strong> &middot; {new Date().getFullYear()}
                    </p>
                </div>
            </footer>
        </div>
    );
};

export default Layout;
