/**
 * -----------------------------------------------------------------------------
 * Generated by Pure Clean Architecture CLI.
 *
 * This file is an example implementation provided to demonstrate
 * how this layer works within the architecture.
 *
 * It is only a starting point — you are free to modify, replace,
 * or delete it as your project evolves.
 * -----------------------------------------------------------------------------
 */

import type { IUserRepository } from '../..//domain';
import type { UserDto } from '../../domain/user.dto';

export class GetUserUseCase {
    constructor(private readonly repository: IUserRepository) {}

    public async execute(id: string): Promise<UserDto> {
        return this.repository.findById({ pathParams: { id } });
    }
}

export class GetUsersUseCase {
    constructor(private readonly repository: IUserRepository) {}

    public async execute(): Promise<UserDto[]> {
        return this.repository.findAll();
    }
}
