/**
 * -----------------------------------------------------------------------------
 * Generated by Pure Clean Architecture CLI.
 *
 * This file is an example implementation provided to demonstrate
 * how this layer works within the architecture.
 *
 * It is only a starting point — you are free to modify, replace,
 * or delete it as your project evolves.
 * -----------------------------------------------------------------------------
 */

import type { UpdateUserDto, UserDto } from '../../domain/user.dto';
import type { IUserRepository } from '../..//domain';

export class UpdateUserUseCase {
    constructor(private readonly repository: IUserRepository) {}

    public async execute(dto: UpdateUserDto): Promise<UserDto> {
        return this.repository.update({
            pathParams: { id: dto.id },
            body: { name: dto.name, email: dto.email },
        });
    }
}
